//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rivals
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodeCode
    {
        public string Code { get; set; }
        public string Description { get; set; }
        public int Amount { get; set; }
        public Nullable<bool> IndDays { get; set; }
        public Nullable<bool> IndWeeks { get; set; }
        public Nullable<bool> IndMonths { get; set; }
        public Nullable<bool> IndYears { get; set; }
    }
}
