//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rivals
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingProduct
    {
        public int TrainingProductId { get; set; }
        public Nullable<int> FK_TrainingId { get; set; }
        public Nullable<int> FK_ProductId { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Training Training { get; set; }
    }
}
