//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rivals
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingRegistration
    {
        public int TrainingRegistrationId { get; set; }
        public int FK_TrainingId { get; set; }
        public string FK_Username { get; set; }
        public System.DateTime registrationDate { get; set; }
        public bool IndConfirmed { get; set; }
        public Nullable<bool> IndAfwezig { get; set; }
    
        public virtual Training Training { get; set; }
    }
}
